# Generated by Django 6.1 on 2026-08-31 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Temblor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('magnitud', models.FloatField(verbose_name='Magnitud')),
                ('profundidad', models.FloatField(verbose_name='Profundidad (km)')),
                ('rango', models.CharField(max_length=50, verbose_name='Rango')),
                ('lugar', models.CharField(max_length=150, verbose_name='Lugar')),
                ('area', models.CharField(max_length=100, verbose_name='Área')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('hora', models.TimeField(verbose_name='Hora')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
            ],
        ),
    ]
