# Generated by Django 6.1 on 2026-08-21 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mi_curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_capacitacion', models.CharField(max_length=255)),
                ('duracion', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('detalle', models.TextField()),
                ('instructor', models.CharField(max_length=300)),
                ('competencia', models.CharField(max_length=500)),
                ('ambiente', models.CharField(max_length=200)),
                ('aprendiz', models.CharField(max_length=300)),
            ],
        ),
    ]
