# Generated by Django 6.1 on 2026-09-04 14:09

import django.core.validators
import django.db.models.deletion
import pathlib
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.SlugField(max_length=40, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de categoría')),
                ('descripcion', models.TextField(blank=True, help_text='Describe el tipo de servicio.')),
                ('activa', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Categoría de servicio',
                'verbose_name_plural': 'Categorías de servicio',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CentroOperativo',
            fields=[
                ('codigo', models.CharField(db_column='codigo_centro', max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
                ('direccion', models.CharField(max_length=250)),
                ('ciudad', models.CharField(db_index=True, max_length=80)),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
                ('configuracion', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Centro operativo',
                'verbose_name_plural': 'Centros operativos',
                'ordering': ['ciudad', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Operador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.PositiveBigIntegerField(unique=True)),
                ('nombre', models.CharField(max_length=120)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('foto', models.ImageField(blank=True, upload_to='operadores/')),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='RegistroTiposDato',
            fields=[
                ('codigo', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ruta_archivo', models.FilePathField(blank=True, path=pathlib.PureWindowsPath('D:/1. Daniel Figueroa/Trabajos/programacion/2. Proyectos/Python/Proyectos Clases Rider/WaySmart'))),
                ('decimal', models.FloatField(default=0.0)),
                ('direccion_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, upload_to='registros/')),
                ('entero', models.IntegerField(default=0)),
                ('datos_json', models.JSONField(blank=True, default=dict)),
                ('entero_grande_positivo', models.PositiveBigIntegerField(default=0)),
                ('entero_positivo', models.PositiveIntegerField(default=0)),
                ('entero_pequeno_positivo', models.PositiveSmallIntegerField(default=0)),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('entero_pequeno', models.SmallIntegerField(default=0)),
                ('texto', models.TextField(blank=True)),
                ('hora', models.TimeField(blank=True, null=True)),
                ('url', models.URLField(blank=True, max_length=300)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Registro de tipos de dato',
                'verbose_name_plural': 'Registros de tipos de dato',
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('tipo', models.CharField(choices=[('moto', 'Motocicleta'), ('van', 'Van'), ('camion', 'Camión')], default='moto', max_length=10)),
                ('capacidad_kg', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('disponible', models.BooleanField(default=True)),
                ('ficha_tecnica', models.FilePathField(blank=True, match='.*\\\\.(pdf|txt)$', path=pathlib.PureWindowsPath('D:/1. Daniel Figueroa/Trabajos/programacion/2. Proyectos/Python/Proyectos Clases Rider/WaySmart'))),
            ],
            options={
                'ordering': ['placa'],
            },
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('codigo', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Código de envío')),
                ('referencia', models.CharField(db_index=True, max_length=50, unique=True)),
                ('descripcion', models.TextField(help_text='Contenido y observaciones del paquete.')),
                ('estado', models.CharField(choices=[('programado', 'Programado'), ('en_ruta', 'En ruta'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='programado', max_length=12)),
                ('peso_kg', models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)])),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('prioridad', models.SmallIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1)])),
                ('hora_recoleccion', models.TimeField(blank=True, null=True)),
                ('seguimiento_url', models.URLField(blank=True, max_length=300)),
                ('comprobante', models.ImageField(blank=True, upload_to='comprobantes/')),
                ('datos_extra', models.JSONField(blank=True, default=dict)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True, db_comment='Última modificación del envío')),
                ('categoria', models.ForeignKey(limit_choices_to={'activa': True}, on_delete=django.db.models.deletion.PROTECT, related_name='envios', related_query_name='envio', to='app_operaciones_logisticas.categoriaservicio')),
                ('centro', models.ForeignKey(db_column='centro_codigo', on_delete=django.db.models.deletion.PROTECT, related_name='envios', to='app_operaciones_logisticas.centrooperativo')),
                ('operador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='envios', to='app_operaciones_logisticas.operador')),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='envios', to='app_operaciones_logisticas.vehiculo')),
            ],
            options={
                'db_table': 'operaciones_envio',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Parada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secuencia', models.PositiveSmallIntegerField()),
                ('destinatario', models.CharField(max_length=150)),
                ('direccion', models.CharField(max_length=300)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('latitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('visitada', 'Visitada'), ('fallida', 'Fallida')], default='pendiente', max_length=10)),
                ('observaciones', models.TextField(blank=True)),
                ('envio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paradas', to='app_operaciones_logisticas.envio')),
            ],
            options={
                'ordering': ['envio', 'secuencia'],
                'constraints': [models.UniqueConstraint(fields=('envio', 'secuencia'), name='parada_unica_por_envio')],
            },
        ),
    ]
