# Generated by Django 6.1 on 2026-09-04 14:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_operaciones_logisticas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40, unique=True)),
                ('color', models.CharField(default='#0d766f', help_text='Color hexadecimal, por ejemplo #0d766f.', max_length=7)),
            ],
        ),
        migrations.AddField(
            model_name='envio',
            name='etiquetas',
            field=models.ManyToManyField(blank=True, related_name='envios', to='app_operaciones_logisticas.etiqueta'),
        ),
        migrations.CreateModel(
            name='PerfilOperador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zona_preferida', models.CharField(max_length=80)),
                ('calificacion', models.FloatField(default=5.0, validators=[django.core.validators.MinValueValidator(0)])),
                ('biografia', models.TextField(blank=True)),
                ('operador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to='app_operaciones_logisticas.operador')),
            ],
        ),
    ]
